# Generated by Django 4.2.5 on 2023-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(blank=True, to="events.clubuser"),
        ),
    ]
