# Generated by Django 4.2.5 on 2023-09-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_venue_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="owner",
            field=models.IntegerField(verbose_name="Venue Owner"),
        ),
    ]
