# Generated by Django 4.2.5 on 2023-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_attendees_alter_event_manager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClubUser",
        ),
        migrations.AddField(
            model_name="venue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
